### ISSUE TITLE
ProfileConstraints marked as number, should probably be different structure

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [PlayFab/NodeSDK#103]
https://github.com/PlayFab/NodeSDK/blob/efae7f183df35e5e8d15c93712b679735d74180e/PlayFabSdk/Scripts/typings/PlayFab/PlayFabServer.d.ts#L2241

According to [the docs](https://docs.microsoft.com/en-us/rest/api/playfab/server/player-data-management/getleaderboard?view=playfab-rest#playerprofileviewconstraints), this property should be an object with one of [the following values](https://docs.microsoft.com/en-us/rest/api/playfab/server/player-data-management/getleaderboard?view=playfab-rest#playerprofileviewconstraints).

Not sure if this is an auto-generated file, or someone is managing it, but would be nice to get it updated somehow.

**Comment by pgilmorepf** [comment]
It is auto generated.
Can you provide an example of the correct typescript definition that should replace this one?

**Comment by stephan-nordnes-eriksen** [comment]
Based on what I find on the documentation, I believe the below to be correct.

```ts
export interface PlayerProfileViewConstraints {
    // From documentation found here: https://docs.microsoft.com/en-us/rest/api/playfab/server/player-data-management/getleaderboard?view=playfab-rest#playerprofileviewconstraints

    // Whether to show player's avatar URL. Defaults to false
    ShowAvatarUrl?: boolean;
    // Whether to show the banned until time. Defaults to false
    ShowBannedUntil?: boolean;
    // Whether to show campaign attributions. Defaults to false
    ShowCampaignAttributions?: boolean;
    // Whether to show contact email addresses. Defaults to false
    ShowContactEmailAddresses?: boolean;
    // Whether to show the created date. Defaults to false
    ShowCreated?: boolean;
    // Whether to show the display name. Defaults to false
    ShowDisplayName?: boolean;
    // Whether to show player's experiment variants. Defaults to false
    ShowExperimentVariants?: boolean;
    // Whether to show the last login time. Defaults to false
    ShowLastLogin?: boolean;
    // Whether to show the linked accounts. Defaults to false
    ShowLinkedAccounts?: boolean;
    // Whether to show player's locations. Defaults to false
    ShowLocations?: boolean;
   // Whether to show player's membership information. Defaults to false
    ShowMemberships?: boolean;
    // Whether to show origination. Defaults to false
    ShowOrigination?: boolean;
    // Whether to show push notification registrations. Defaults to false
    ShowPushNotificationRegistrations?: boolean;
    // Reserved for future development
    ShowStatistics?: boolean;
    // Whether to show tags. Defaults to false
    ShowTags?: boolean;
    // Whether to show the total value to date in usd. Defaults to false
    ShowTotalValueToDateInUsd?: boolean;
    // Whether to show the values to date. Defaults to false
    ShowValuesToDate?: boolean;
}
```

Then this line:
https://github.com/PlayFab/NodeSDK/blob/efae7f183df35e5e8d15c93712b679735d74180e/PlayFabSdk/Scripts/typings/PlayFab/PlayFabServer.d.ts#L2241


Would become:

```ts
ProfileConstraints?: PlayerProfileViewConstraints;
```

**Comment by lazerwalker** [comment]
Wanted to +1 this, I've got shipped production code where we're manually casting to a number to avoid this incorrect type error: https://github.com/flappy-royale/flappy-royale/blob/master/src/playFab.ts#L220-L223

**Comment by lazerwalker** [comment]
FYI, this appears to be an issue at the SDK generation level. You'll note that type definitions for `PlayerProfileViewConstraints` exist in e.g. PlayFabServer.ts, it's just that any property key that should have it as a type has `number` instead.

Opened a pull request upstream in the SDK generator that should fix this.

**Comment by pgilmorepf** [comment]
Thanks for the bug report, and thanks to @lazerwalker for sending us the fix.
Release: https://github.com/PlayFab/NodeSDK/releases/tag/2.46.200422
Release Notes: https://docs.microsoft.com/en-us/gaming/playfab/release-notes/#200422
NPM Package: https://www.npmjs.com/package/playfab-sdk

**Comment by henriquecarv** [comment]
Just a heads up. This issue is still unsolved 🤔

**Comment by pgilmorepf** [comment]
I just looked at PlayFabServer.d.ts master branch, and I see it as fixed:
https://github.com/PlayFab/NodeSDK/blob/master/PlayFabSdk/Scripts/typings/PlayFab/PlayFabServer.d.ts#L2540
Can you explain where/how it's not fixed?

**Comment by henriquecarv** [comment]
It's correct that `ProfileConstraints` have been modified to be an optional property at:
https://github.com/PlayFab/NodeSDK/blob/master/PlayFabSdk/Scripts/typings/PlayFab/PlayFabServer.d.ts#L2540
https://github.com/PlayFab/NodeSDK/blob/master/PlayFabSdk/Scripts/typings/PlayFab/PlayFabServer.d.ts#L2639

The adjustments we seem to be missing is for each property inside the `PlayerProfileViewConstraints` interface to be optional:
https://github.com/PlayFab/NodeSDK/blob/1d648c0b0a4e70f806eed1533b11bfd474644aba/PlayFabSdk/Scripts/typings/PlayFab/PlayFabServer.d.ts#L3634

As mentioned in the OP's [comment](https://github.com/PlayFab/NodeSDK/issues/103#issuecomment-602448443)
